name: test
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'
      - name: Install Cookiecutter
        run: |
          apt-get update && apt-get install -y python3-pip git
          pip3 install cookiecutter --break-system-packages
      - name: run tests
        run: make test